name: Update Currency Rates
on:
  schedule:
    - cron: '0 0 * * *' # প্রতিদিন রাত ১২টায় রান হবে
  workflow_dispatch: # ম্যানুয়ালি রান করার অপশন

jobs:
  update-rates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch Currency Rates
        run: |
          curl -s "https://v6.exchangerate-api.com/v6/${{ secrets.CURRENCY_API_KEY }}/latest/BDT" > rates.json

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add rates.json
          git commit -m "Update rates" || exit 0
          git push
